name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        goos: [ linux, windows, darwin ]
        goarch: [ amd64, 386 ]
        name: ${{ matrix.goos }}-${{ matrix.goarch }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Download dependencies
        run: go mod download
      - name: Cross compilation
        run: go build -v -o ./bin/${{ matrix.name }}/oplus-updater ./main.go
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: oplus-updater-${{ matrix.name }}
          path: bin/${{ matrix.name }}/oplus-updater
